#!/bin/bash
echo "========================================"
echo "GitHub Push Script"
echo "========================================"
echo ""
echo "Repository: https://github.com/Jmsconsultancy2025/worksite-manager"
echo "Token: ghp_w9Ataodmypc6Efgcb8fB2PVnGcjIcp0HYs5H"
echo ""
echo "Run these commands:"
echo ""
echo "cd /app"
echo "git remote set-url origin https://Jmsconsultancy2025:ghp_w9Ataodmypc6Efgcb8fB2PVnGcjIcp0HYs5H@github.com/Jmsconsultancy2025/worksite-manager.git"
echo "git push -u origin main"
echo ""
echo "Or manually:"
echo "1. Go to https://github.com/Jmsconsultancy2025/worksite-manager"
echo "2. Click 'uploading an existing file'"
echo "3. Drag all files from /app to GitHub"
echo ""
